version: '3.8'
services:
  mongodb:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - '27017:27017'  # Expose MongoDB on the default port
    volumes:
      - mongodb_data:/data/db  # Persist data even when container stops

volumes:
  mongodb_data:  # Volume to persist MongoDB data
